export const SITE = {
  website: "https://hackthebrain.dev/",
  author: "NETZY",
  profile: "https://github.com/n3tzy",
  desc: "NETZY의 AI Security 연구와 기술 기록. LLM 보안 진단, AI Red Teaming, 검증 가능한 공격 시나리오를 다룹니다.",
  title: "hackthebrain",
  ogImage: "og.png",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "https://github.com/n3tzy/hackthebrain/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "ko",
  timezone: "Asia/Seoul",
} as const;
